version: '3.8'

services:
  nodeapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: sapassword
      DB_NAME: testdb
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: testdb